language: python
os:
  - linux
python:
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install poetry coveralls
  - poetry install
script:
  - mypy dialogy
  - pytest --cov=dialogy
after_success:
  - coveralls
