[tool.poetry]
name = "dialogy"
version = "0.1.0"
description = "Language understanding for human dialog."
authors = ["Amresh Venugopal <amresh.venugopal@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
coloredlogs = "^15.0"
attrs = "^20.3.0"
requests = "^2.25.1"
pytz = "^2020.4"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.0"
pytest-cov = "^2.10.1"
mypy = "^0.790"
httpretty = "^1.0.3"
black = "^20.8b1"
rope = "^0.18.0"
bandit = "^1.7.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
