[tool.poetry]
name = "dialogy"
version = "0.1.0"
description = "Language understanding for human dialog."
authors = ["Amresh Venugopal <amresh.venugopal@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
coloredlogs = "^15.0"
attrs = "^20.3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.0"
pytest-cov = "^2.10.1"
pylint = "^2.6.0"
mypy = "^0.790"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
